AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Resume Details Service
  * List of services used:
    * API Gateway
    * Lambdas
    * DDB Tables
    * S3 buckets

  Sample SAM Template for AWS

Parameters:
  Environment:
    Description: Environment
    Default: dev
    Type: String
    AllowedValues:
      - prod
      - test
      - dev
    ConstraintDescription: Must specify a valid environment dev, test or prod.
  WebsiteBucketName:
    Description: Unique name for the website bucket
    Type: String
  ConfigurationBucketName:
    Description: Unique name for the configuration bucket
    Type: String

Resources:
  ApiStack:
    Type: AWS::CloudFormation::Stack
    DependsOn:
      - TablesStack
      - SharedLayersStack
    Properties:
      TemplateURL: !Join ["", ['https://s3.us-east-1.amazonaws.com/', !Ref 'ConfigurationBucketName', '/templates/api/packaged.yaml']]
      Parameters:
        Environment: !Ref Environment
        ConfigurationBucketName: !Ref ConfigurationBucketName
        AwsLayer: !GetAtt SharedLayersStack.Outputs.AwsLayer
        ExperiencesTable: !GetAtt TablesStack.Outputs.ExperiencesTable

  TablesStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Join ["", ['https://s3.us-east-1.amazonaws.com/', !Ref 'ConfigurationBucketName', '/templates/tables/packaged.yaml']]
      Parameters:
        Environment: !Ref Environment

  SharedLayersStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Join ["", ['https://s3.us-east-1.amazonaws.com/', !Ref 'ConfigurationBucketName', '/templates/sharedLayer/packaged.yaml']]
      Parameters:
        Environment: !Ref Environment

  StorageStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Join ["", ['https://s3.us-east-1.amazonaws.com/', !Ref 'ConfigurationBucketName', '/templates/storage/packaged.yaml']]
      Parameters:
        Environment: !Ref Environment
        BucketName: !Ref WebsiteBucketName

Outputs:
  ApiUri:
    Description: "API Gateway endpoint URI"
    Value: !GetAtt ApiStack.Outputs.ApiUri
  WebsiteULR:
    Description: "Resume Website URL"
    Value: !GetAtt StorageStack.Outputs.WebsiteURL
