AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Resume Demo App DynamoDB Tables

  SAM Template for AWS

Parameters:
  Environment:
    Description: Environment
    Default: dev
    Type: String
    AllowedValues:
      - prod
      - test
      - dev
    ConstraintDescription: Must specify a valid environment dev, test or prod.

Mappings:
  ResumeMap:
    experiencesTable:
      name: resume_demo_experiences_table

Resources:
  ExperiencesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Join ["_", [!FindInMap [ResumeMap, experiencesTable, name], !Ref 'Environment']]
      AttributeDefinitions:
        - AttributeName: PK
          AttributeType: S
      KeySchema:
        - AttributeName: PK
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

Outputs:
  ExperiencesTable:
    Description: "Experiences table"
    Value: !Ref ExperiencesTable
  ExperiencesTableArn:
    Description: "Experiences table ARN"
    Value: !GetAtt ExperiencesTable.Arn
