AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Resume Demo App API Configuration

  SAM Template for AWS

Globals:
  Function:
    Runtime: nodejs12.x
    Timeout: 3
    Handler: handler.lambdaHandler
    Environment:
      Variables:
        TABLE_NAME: !Ref ExperiencesTable

Parameters:
  Environment:
    Description: Environment
    Default: dev
    Type: String
    AllowedValues:
      - prod
      - test
      - dev
    ConstraintDescription: Must specify a valid environment dev, test or prod.
  AwsLayer:
    Type: String
  ExperiencesTable:
    Type: String

Mappings:
  CreateExperienceMap:
    ApiFunction:
      name: resume_demo_api_CreateExperience_fn
  GetExperiencesMap:
    ApiFunction:
      name: resume_demo_api_GetExperiences_fn

Resources:
  ResumeDemoApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      StageName: !Ref Environment
      DefinitionBody:
        'Fn::Transform':
          Name: AWS::Include
          Parameters:
            # Location: !Join ["", 's3://resume-demo-configs-', !Ref 'Environment', '/templates/api/api-definition.yaml']
            Location: 's3://resume-demo-configs-dev/templates/api/api-definition.yaml'

  CreateExperienceFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      FunctionName: !Join ["_", [!FindInMap [CreateExperienceMap, ApiFunction, name], !Ref 'Environment']]
      CodeUri: ../../src/resumeService/addExperience
      Events:
        ExperienceEvent:
          Type: HttpApi
          Properties:
            Path: /experiences
            Method: POST
            ApiId: !Ref ResumeDemoApi
        EducationEvent:
          Type: HttpApi
          Properties:
            Path: /educations
            Method: POST
            ApiId: !Ref ResumeDemoApi
      Layers:
        - !Ref AwsLayer
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref ExperiencesTable

  GetExperienceFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      FunctionName: !Join ["_", [!FindInMap [GetExperiencesMap, ApiFunction, name], !Ref 'Environment']]
      CodeUri: ../../src/resumeService/getExperience
      Events:
        GetExperienceEvent:
          Type: HttpApi
          Properties:
            Path: /experiences/{experienceId}
            Method: GET
            ApiId: !Ref ResumeDemoApi
        GetExperiencesEvent:
          Type: HttpApi
          Properties:
            Path: /experiences
            Method: GET
            ApiId: !Ref ResumeDemoApi
        GetEducationEvent:
          Type: HttpApi
          Properties:
            Path: /educations/{educationId}
            Method: GET
            ApiId: !Ref ResumeDemoApi
        GetEducationsEvent:
          Type: HttpApi
          Properties:
            Path: /educations
            Method: GET
            ApiId: !Ref ResumeDemoApi
      Layers:
        - !Ref AwsLayer
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref ExperiencesTable

Outputs:
  ApiUri:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${ResumeDemoApi}.execute-api.${AWS::Region}.${AWS::URLSuffix}/${Environment}"

  CreateExperienceFunction:
    Description: "Create Experience Lambda Function ARN"
    Value: !GetAtt CreateExperienceFunction.Arn

  GetExperienceFunction:
    Description: "Get Experience Lambda Function ARN"
    Value: !GetAtt GetExperienceFunction.Arn
